import logging
from typing import Dict, Any, List

class YogaEngine:
    """
    Deterministic evaluation of top classical Parashari Yogas.
    Calculates the presence and mathematical potency of yogas using
    structural combinations (Kendras, Trikonas, Dusthanas, aspects, dignity)
    and the raw planet_results generated by the PlanetStrengthEngine.
    """

    def __init__(self):
        self.kendra_houses = [1, 4, 7, 10]
        self.trikona_houses = [1, 5, 9]
        self.dusthana_houses = [6, 8, 12]
        self.wealth_houses = [2, 11]
        
        self.pancha_mahapurusha_map = {
            "mars": "Ruchaka Yoga",
            "mercury": "Bhadra Yoga",
            "jupiter": "Hamsa Yoga",
            "venus": "Malavya Yoga",
            "saturn": "Shasha Yoga"
        }

    def evaluate(self, normalized_payload: Dict[str, Any], planet_results: Dict[str, Any], house_results: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        Evaluate structural yogas.
        
        Returns:
            dict: {
                "active_yogas": [
                    {
                        "yoga_name": str,
                        "category": str,
                        "strength": float,
                        "contributing_planets": List[str],
                        "contributing_houses": List[int],
                        "explanation": str
                    }
                ],
                "category_summaries": {
                    "Raja Yoga": {"count": int, "max_strength": float},
                    ...
                }
            }
        """
        active_yogas = []
        
        # We need a quick lookup of planet to its current house
        planet_house_map = {
            p: data.get("house")
            for p, data in normalized_payload.get("planets", {}).items()
            if data.get("house")
        }
        
        # We need a quick lookup of house to its lord
        house_lord_map = {
            int(h): data.get("lord")
            for h, data in normalized_payload.get("houses", {}).items()
            if data.get("lord")
        }
        
        active_yogas.extend(self._eval_pancha_mahapurusha(normalized_payload, planet_results, planet_house_map))
        active_yogas.extend(self._eval_gaja_kesari(normalized_payload, planet_results, planet_house_map))
        active_yogas.extend(self._eval_vipareeta_raja(normalized_payload, planet_results, planet_house_map, house_lord_map))
        active_yogas.extend(self._eval_dhana_yogas(normalized_payload, planet_results, planet_house_map, house_lord_map))
        active_yogas.extend(self._eval_raja_yogas(normalized_payload, planet_results, planet_house_map, house_lord_map))
        active_yogas.extend(self._eval_neecha_bhanga(normalized_payload, planet_results, planet_house_map))
        active_yogas.extend(self._eval_arishta_yogas(normalized_payload, planet_results, planet_house_map))

        # Build summaries
        categories = ["Pancha Mahapurusha Yoga", "Gaja Kesari Yoga", "Vipareeta Raja Yoga", 
                      "Dhana Yoga", "Raja Yoga", "Neecha Bhanga Raja Yoga", "Arishta Yoga"]
        category_summaries = {c: {"count": 0, "max_strength": 0.0} for c in categories}
        
        for y in active_yogas:
            cat = y["category"]
            if cat not in category_summaries:
                category_summaries[cat] = {"count": 0, "max_strength": 0.0}
            category_summaries[cat]["count"] += 1
            if y["strength"] > category_summaries[cat]["max_strength"]:
                category_summaries[cat]["max_strength"] = round(y["strength"], 2)

        return {
            "active_yogas": active_yogas,
            "category_summaries": category_summaries
        }

    def _get_avg_strength(self, planets: List[str], planet_results: Dict[str, Any]) -> float:
        if not planets:
            return 0.0
        total = sum(planet_results.get(p, {}).get("final_score", 50.0) for p in planets)
        return total / len(planets)

    def _eval_pancha_mahapurusha(self, payload: dict, p_results: dict, p_houses: dict) -> list:
        yogas = []
        for p in ["mars", "mercury", "jupiter", "venus", "saturn"]:
            if p not in p_houses:
                continue
            house = p_houses[p]
            dignity = payload.get("planets", {}).get(p, {}).get("dignity", "neutral").lower().replace(" ", "_")
            
            if house in self.kendra_houses and dignity in ["exalted", "own_sign", "moolatrikona"]:
                yogas.append({
                    "yoga_name": self.pancha_mahapurusha_map[p],
                    "category": "Pancha Mahapurusha Yoga",
                    "strength": self._get_avg_strength([p], p_results),
                    "contributing_planets": [p],
                    "contributing_houses": [house],
                    "explanation": f"{p.capitalize()} is in a Kendra (House {house}) and is in high dignity ({dignity})."
                })
        return yogas

    def _eval_gaja_kesari(self, payload: dict, p_results: dict, p_houses: dict) -> list:
        yogas = []
        jup_h = p_houses.get("jupiter")
        moon_h = p_houses.get("moon")
        if jup_h and moon_h:
            # Kendra from Moon logic: distance between moon and jup must be 1, 4, 7, or 10
            # house = ((jup_h - moon_h + 12) % 12) + 1
            dist = ((jup_h - moon_h + 12) % 12) + 1
            if dist in self.kendra_houses:
                # Neither debilitated
                jup_dignity = payload.get("planets", {}).get("jupiter", {}).get("dignity", "neutral").lower()
                moon_dignity = payload.get("planets", {}).get("moon", {}).get("dignity", "neutral").lower()
                if jup_dignity != "debilitated" and moon_dignity != "debilitated":
                    yogas.append({
                        "yoga_name": "Gaja Kesari Yoga",
                        "category": "Gaja Kesari Yoga",
                        "strength": self._get_avg_strength(["jupiter", "moon"], p_results),
                        "contributing_planets": ["jupiter", "moon"],
                        "contributing_houses": [jup_h, moon_h],
                        "explanation": f"Jupiter is in a Kendra from the Moon (House {jup_h} and House {moon_h})."
                    })
        return yogas

    def _eval_vipareeta_raja(self, payload: dict, p_results: dict, p_houses: dict, h_lords: dict) -> list:
        yogas = []
        for d_house in self.dusthana_houses:
            lord = h_lords.get(d_house)
            if lord and lord in p_houses:
                lord_h = p_houses[lord]
                if lord_h in self.dusthana_houses and lord_h != d_house:
                    # Lord of dusthana in another dusthana
                    yoga_name = "Vipareeta Raja Yoga"
                    if d_house == 6: yoga_name = "Harsha Yoga"
                    elif d_house == 8: yoga_name = "Sarala Yoga"
                    elif d_house == 12: yoga_name = "Vimala Yoga"
                    
                    yogas.append({
                        "yoga_name": yoga_name,
                        "category": "Vipareeta Raja Yoga",
                        "strength": self._get_avg_strength([lord], p_results),
                        "contributing_planets": [lord],
                        "contributing_houses": [lord_h, d_house],
                        "explanation": f"The lord of Dusthana House {d_house} ({lord.capitalize()}) is placed in another Dusthana House {lord_h}."
                    })
        return yogas

    def _check_relationship(self, p1: str, p2: str, p_houses: dict, payload: dict) -> str:
        """Returns 'conjunction', 'exchange', 'mutual_aspect', or ''."""
        if p1 == p2:
            return ""
            
        h1 = p_houses.get(p1)
        h2 = p_houses.get(p2)
        if not h1 or not h2:
            return ""
            
        # Conjunction
        if h1 == h2:
            return "conjunction"
            
        # Exchange
        h_lords = {int(h): d.get("lord") for h, d in payload.get("houses", {}).items() if d.get("lord")}
        if h_lords.get(h1) == p2 and h_lords.get(h2) == p1:
            return "exchange"
            
        # Mutual Aspect (Standard 7th aspect)
        # We simplify to 7th aspect for deterministic standard
        dist = ((h1 - h2 + 12) % 12) + 1
        if dist == 7:
            return "mutual_aspect"
            
        return ""

    def _eval_dhana_yogas(self, payload: dict, p_results: dict, p_houses: dict, h_lords: dict) -> list:
        yogas = []
        trikona_lords = [h_lords.get(h) for h in self.trikona_houses if h_lords.get(h)]
        wealth_lords = [h_lords.get(h) for h in self.wealth_houses if h_lords.get(h)]
        
        seen_pairs = set()
        
        for t_lord in trikona_lords:
            for w_lord in wealth_lords:
                if t_lord == w_lord or not t_lord or not w_lord:
                    continue
                    
                pair = tuple(sorted([t_lord, w_lord]))
                if pair in seen_pairs:
                    continue
                    
                rel = self._check_relationship(t_lord, w_lord, p_houses, payload)
                if rel:
                    seen_pairs.add(pair)
                    yogas.append({
                        "yoga_name": f"Dhana Yoga ({rel})",
                        "category": "Dhana Yoga",
                        "strength": self._get_avg_strength([t_lord, w_lord], p_results),
                        "contributing_planets": [t_lord, w_lord],
                        "contributing_houses": [p_houses.get(t_lord), p_houses.get(w_lord)],
                        "explanation": f"Lords of Trikona and Wealth houses ({t_lord.capitalize()} and {w_lord.capitalize()}) form a {rel}."
                    })
        return yogas

    def _eval_raja_yogas(self, payload: dict, p_results: dict, p_houses: dict, h_lords: dict) -> list:
        yogas = []
        kendra_lords = [h_lords.get(h) for h in self.kendra_houses if h_lords.get(h)]
        trikona_lords = [h_lords.get(h) for h in self.trikona_houses if h_lords.get(h)]
        
        seen_pairs = set()
        
        for k_lord in kendra_lords:
            for t_lord in trikona_lords:
                if k_lord == t_lord or not k_lord or not t_lord:
                    continue
                    
                pair = tuple(sorted([k_lord, t_lord]))
                if pair in seen_pairs:
                    continue
                    
                rel = self._check_relationship(k_lord, t_lord, p_houses, payload)
                if rel:
                    seen_pairs.add(pair)
                    # Penalty if lord also rules dusthana
                    dusthana_lords = [h_lords.get(h) for h in self.dusthana_houses]
                    base_str = self._get_avg_strength([k_lord, t_lord], p_results)
                    if k_lord in dusthana_lords or t_lord in dusthana_lords:
                        base_str *= 0.8  # 20% penalty
                        
                    yogas.append({
                        "yoga_name": f"Raja Yoga ({rel})",
                        "category": "Raja Yoga",
                        "strength": round(base_str, 2),
                        "contributing_planets": [k_lord, t_lord],
                        "contributing_houses": [p_houses.get(k_lord), p_houses.get(t_lord)],
                        "explanation": f"Lords of Kendra and Trikona ({k_lord.capitalize()} and {t_lord.capitalize()}) form a {rel}."
                    })
        return yogas

    def _eval_neecha_bhanga(self, payload: dict, p_results: dict, p_houses: dict) -> list:
        yogas = []
        h_lords = {int(h): d.get("lord") for h, d in payload.get("houses", {}).items() if d.get("lord")}
        
        for p, res in p_results.items():
            p_dignity = payload.get("planets", {}).get(p, {}).get("dignity", "neutral").lower()
            if p_dignity == "debilitated":
                # Find its dispositor (lord of the house it is in)
                house = p_houses.get(p)
                if not house: continue
                
                dispositor = h_lords.get(house)
                if dispositor and dispositor in p_houses:
                    disp_h = p_houses[dispositor]
                    moon_h = p_houses.get("moon")
                    
                    # Check if dispositor is in kendra from Ascendant or Moon
                    in_kendra_asc = disp_h in self.kendra_houses
                    in_kendra_moon = False
                    if moon_h:
                        dist_m = ((disp_h - moon_h + 12) % 12) + 1
                        in_kendra_moon = dist_m in self.kendra_houses
                        
                    if in_kendra_asc or in_kendra_moon:
                        yogas.append({
                            "yoga_name": "Neecha Bhanga Raja Yoga",
                            "category": "Neecha Bhanga Raja Yoga",
                            "strength": self._get_avg_strength([dispositor], p_results),
                            "contributing_planets": [p, dispositor],
                            "contributing_houses": [house, disp_h],
                            "explanation": f"{p.capitalize()} is debilitated, but its dispositor {dispositor.capitalize()} is in a Kendra, cancelling the debilitation."
                        })
        return yogas

    def _eval_arishta_yogas(self, payload: dict, p_results: dict, p_houses: dict) -> list:
        yogas = []
        malefics = ["saturn", "mars", "rahu", "ketu"]
        benefics = ["jupiter", "venus"]
        
        # Kemadruma Yoga: no planets in 2nd and 12th from Moon
        moon_h = p_houses.get("moon")
        if moon_h:
            h_2 = ((moon_h + 1 - 1) % 12) + 1
            h_12 = ((moon_h - 1 - 1) % 12) + 1
            
            p_in_2 = [p for p, h in p_houses.items() if h == h_2 and p not in ["sun", "rahu", "ketu"]]
            p_in_12 = [p for p, h in p_houses.items() if h == h_12 and p not in ["sun", "rahu", "ketu"]]
            
            if not p_in_2 and not p_in_12:
                # Penalty based on inverse moon strength
                moon_str = p_results.get("moon", {}).get("final_score", 50.0)
                str_val = max(0.0, 100.0 - moon_str)
                yogas.append({
                    "yoga_name": "Kemadruma Yoga",
                    "category": "Arishta Yoga",
                    "strength": round(str_val, 2),
                    "contributing_planets": ["moon"],
                    "contributing_houses": [moon_h],
                    "explanation": "No planets in the 2nd and 12th from the Moon, causing mental isolation."
                })
                
        # Papakartari Yoga: Ascendant or Moon flanked by malefics
        # E.g. for Ascendant (H1), malefics in H12 and H2.
        for h_focus, target in [(1, "Ascendant"), (moon_h, "Moon")]:
            if not h_focus: continue
            h_prev = ((h_focus - 1 - 1) % 12) + 1
            h_next = ((h_focus + 1 - 1) % 12) + 1
            
            malefics_in_prev = [p for p in malefics if p_houses.get(p) == h_prev]
            malefics_in_next = [p for p in malefics if p_houses.get(p) == h_next]
            
            if malefics_in_prev and malefics_in_next:
                # Ensure no benefics are there to break it
                benefics_in_prev = [p for p in benefics if p_houses.get(p) == h_prev]
                benefics_in_next = [p for p in benefics if p_houses.get(p) == h_next]
                
                if not benefics_in_prev and not benefics_in_next:
                    c_planets = malefics_in_prev + malefics_in_next
                    yogas.append({
                        "yoga_name": f"Papakartari Yoga ({target})",
                        "category": "Arishta Yoga",
                        "strength": self._get_avg_strength(c_planets, p_results),
                        "contributing_planets": c_planets,
                        "contributing_houses": [h_prev, h_next],
                        "explanation": f"The {target} is flanked by malefics in the adjacent houses."
                    })

        return yogas
