from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional

class ChartProcessRequest(BaseModel):
    """
    The exact two JSON payloads generated by the independent HoroscopeCleaner_Final.
    """
    canonical_content: Dict[str, Any] = Field(..., description="Raw chart data from HoroscopeCleaner")
    machine_index: Any = Field(default=None, description="Extracted table definitions from HoroscopeCleaner (Cosmetic only)")

class ChartProcessResponse(BaseModel):
    """
    The synchronous output from the PipelineRunner, serving the complete
    astrological calculation.
    """
    status: str = "COMPLETED"
    final_score: float = Field(..., description="Master Probability Score (0-100)")
    probability_grade: str = Field(..., description="Grade (e.g., EXCELLENT, WEAK)")
    breakdown: Dict[str, Any] = Field(..., description="Detailed nested breakdown of engines")
    yogas: List[Dict[str, Any]] = Field(default_factory=list, description="Array of detected yogas and explanations")
