from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional
import uuid

class QuestionRequest(BaseModel):
    """
    Because the API is completely stateless, the client must pass the full 
    calculated prediction payload back to the server when asking a question.
    """
    question_text: Optional[str] = Field(None, description="User's natural language question")
    question_id: Optional[str] = Field(None, description="Specific Question ID from the Question Registry")
    engine_outputs: Dict[str, Any] = Field(..., description="The complete ChartProcessResponse breakdown from a previous calculation")

class QuestionResponse(BaseModel):
    """
    Narrative response generated by the LLM based purely on the deterministic
    mathematics provided.
    """
    question_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    resolved_question_id: Optional[str] = Field(None, description="The matched deterministic question ID")
    answer_text: str = Field(..., description="Narrative response generated by QuestionEngine")
    referenced_yogas: List[str] = Field(default_factory=list, description="List of classical yogas quoted in the answer")

class PromiseAssessmentDisplay(BaseModel):
    promise_score: str
    promise_grade: str
    interpretation: str

class DashaActivationDisplay(BaseModel):
    mahadasha: str
    antardasha: str
    pratyantardasha: str
    activation_index: str
    activation_grade: str

class FinalConclusionDisplay(BaseModel):
    promise_status: str
    dasha_support: str
    assessment: str

class TimingWindowDisplay(BaseModel):
    mahadasha: str
    antardasha: str
    pratyantardasha: str
    most_supportive_period: str

class StructuredQuestionResult(BaseModel):
    question_title: str
    promise_assessment: PromiseAssessmentDisplay
    dasha_activation: DashaActivationDisplay
    final_conclusion: FinalConclusionDisplay
    timing_window: TimingWindowDisplay
    supporting_factors: List[str]
    attention_factors: List[str]
    mandali_commentary: str = "Reserved for Phase 15. Do not implement yet."

class StructuredQuestionResponse(BaseModel):
    question_id: str
    results: List[StructuredQuestionResult]
