from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional
import uuid

class QuestionRequest(BaseModel):
    """
    Because the API is completely stateless, the client must pass the full 
    calculated prediction payload back to the server when asking a question.
    """
    question_text: Optional[str] = Field(None, description="User's natural language question")
    question_id: Optional[str] = Field(None, description="Specific Question ID from the Question Registry")
    engine_outputs: Dict[str, Any] = Field(..., description="The complete ChartProcessResponse breakdown from a previous calculation")

class QuestionResponse(BaseModel):
    """
    Narrative response generated by the LLM based purely on the deterministic
    mathematics provided.
    """
    question_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    resolved_question_id: Optional[str] = Field(None, description="The matched deterministic question ID")
    answer_text: str = Field(..., description="Narrative response generated by QuestionEngine")
    referenced_yogas: List[str] = Field(default_factory=list, description="List of classical yogas quoted in the answer")

# --- SECTION A: Executive Summary ---
class ExecutiveSummaryDisplay(BaseModel):
    promise_display: str # e.g. "84% (Excellent)"
    current_support_display: str
    best_future_opportunity_display: str
    best_future_window: str
    main_strength: str
    main_weakness: str
    recommendation: str
    current_period_remaining: str
    overall_lifetime_direction: str

# --- SECTION B: Current Dasha Status ---
class CurrentDashaStatusDisplay(BaseModel):
    current_md: str
    current_ad: str
    current_pd: str
    current_activation_display: str
    current_probability_display: str
    remaining_duration: str
    ends_on: str

# --- SECTION C: Future Opportunity Windows ---
class FutureOpportunityWindowDisplay(BaseModel):
    rank: int
    start_date: str # e.g. 29 May 2047
    end_date: str
    age: str
    mahadasha: str
    antardasha: str
    pratyantardasha: str
    final_probability_display: str
    astrological_driver: str

# --- SECTION D: Detailed Astrological Analysis ---
class DetailedAnalysisDisplay(BaseModel):
    natural_language_explanation: str

# --- SECTION E: Supporting Factors ---
class SupportingFactorDisplay(BaseModel):
    title: str
    explanation: str
    impact: str

# --- SECTION F: Attention Factors ---
class AttentionFactorDisplay(BaseModel):
    reason: str
    impact: str
    severity: str
    recommendation: str

# --- SECTION G: Lifetime Summary ---
class LifetimeSummaryDisplay(BaseModel):
    strong_period_count: int
    moderate_period_count: int
    weak_period_count: int
    highest_activation_display: str
    highest_probability_display: str
    best_lifetime_window: str
    longest_strong_window: str
    current_lifetime_rank: str

# --- SECTION H: Technical Lifetime MD-AD-PD Strength Analysis ---
class TechnicalLifetimeRecord(BaseModel):
    rank: int
    start_date: str
    end_date: str
    age: str
    mahadasha: str
    md_planet_strength: str
    antardasha: str
    ad_planet_strength: str
    pratyantardasha: str
    pd_planet_strength: str
    dasha_activation_display: str
    final_probability_display: str
    is_current_period: bool
    remaining_duration: Optional[str] = None
    ends_on: Optional[str] = None

# --- SECTION I: Formula Verification ---
class FormulaVerificationDisplay(BaseModel):
    data_lineage: Dict[str, Any]

class StructuredQuestionResult(BaseModel):
    question_title: str
    domain: str
    executive_summary: ExecutiveSummaryDisplay
    current_dasha_status: CurrentDashaStatusDisplay
    future_opportunities: List[FutureOpportunityWindowDisplay]
    detailed_analysis: DetailedAnalysisDisplay
    supporting_factors: List[SupportingFactorDisplay]
    attention_factors: List[AttentionFactorDisplay]
    lifetime_summary: LifetimeSummaryDisplay
    formula_verification: FormulaVerificationDisplay

class StructuredQuestionResponse(BaseModel):
    question_id: str
    results: List[StructuredQuestionResult]
